### MONGO ROUTES

http://localhost:3001/api/schools
###
http://localhost:3001/api/students
###
http://localhost:3001/api/pros
###

### SQL ROUTES

http://localhost:3001/api/disciplines
###
http://localhost:3001/api/teachers/5/training
###
http://localhost:3001/api/students/1/learning
###

http://localhost:3001/api/certifications
###
http://localhost:3001/api/teachers
###
http://localhost:3001/api/students
###
http://localhost:3001/api/students/1
###



POST http://localhost:3001/api/disciplines/new
content-type: application/json

{
    "Name" : "Google Fu",
    "Description" : "Your worst nightmare"
}
###

POST http://localhost:3001/api/students/new
content-type: application/json

{
    "FirstName" : "Foo",
    "LastName" : "Bar"
}

###
POST http://localhost:3001/api/teachers/new
content-type: application/json

{
    "FirstName" : "Michael",
    "LastName" : "Jordan"
}
###